### POST CATEGORY

POST {{url}}/api/categories HTTP/1.1

{
  "english_name": "",
  "name": ""
}


### POST MULTIPLE CATEGORY

POST {{url}}/api/categories/bulk HTTP/1.1

[
  {
    "english_name": "Others",
    "name": "おすすめ"
  },
  {
    "english_name": "Drinks",
    "name": "ドリンク"
  }
]


### GET CATEGORY

GET {{url}}/api/categories HTTP/1.1
