### GET PRODUCT

GET {{url}}/api/product HTTP/1.1


### POST PRODUCT

POST {{url}}/api/product HTTP/1.1
Content-Type: application/json

{
  "category_id": 1,
  "name": "たこやき",
  "price": 600
}


### GET STATIC FILES

GET {{url}}/ HTTP/2
