### VARIIABLE DECLARATION

@url = 127.0.0.1:8080


### GET PRODUCT

GET {{url}}/product HTTP/1.1


### POST PRODUCT

POST {{url}}/product HTTP/1.1
Content-Type: application/json

{
  "name": "Teriyaki",
  "price": 800
}
