// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT
  COUNT(id)
FROM
  users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO
  sessions (created_at, expires_at, user_id, token)
VALUES
  (NOW(), $1, $2, $3)
RETURNING
  token, created_at, expires_at, user_id
`

type CreateSessionParams struct {
	ExpiresAt pgtype.Timestamp
	UserID    pgtype.Int4
	Token     string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.ExpiresAt, arg.UserID, arg.Token)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UserID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO
  users (
    created_at,
    updated_at,
    username,
    password_hash,
    role
  )
VALUES
  (NOW(), NOW(), $1, $2, $3)
RETURNING
  id, created_at, updated_at, username, password_hash, role
`

type CreateUserParams struct {
	Username     string
	PasswordHash string
	Role         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PasswordHash, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE
  token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE
  id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT
  token, created_at, expires_at, user_id
FROM
  sessions
WHERE
  token = $1
`

func (q *Queries) GetSession(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, token)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UserID,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT
  id, created_at, updated_at, username, password_hash, role
FROM
  users
WHERE
  username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}

const updateExpireSession = `-- name: UpdateExpireSession :exec
UPDATE sessions
SET
  expires_at = $1
WHERE
  token = $2
`

type UpdateExpireSessionParams struct {
	ExpiresAt pgtype.Timestamp
	Token     string
}

func (q *Queries) UpdateExpireSession(ctx context.Context, arg UpdateExpireSessionParams) error {
	_, err := q.db.Exec(ctx, updateExpireSession, arg.ExpiresAt, arg.Token)
	return err
}
