// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package database

import (
	"context"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO
  category (created_at, updated_at, name, romaji_name)
VALUES
  (NOW(), NOW(), $1, $2)
RETURNING
  id, created_at, updated_at, name, romaji_name
`

type CreateCategoryParams struct {
	Name       string
	RomajiName string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.Name, arg.RomajiName)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.RomajiName,
	)
	return i, err
}

const deleteCategoryByID = `-- name: DeleteCategoryByID :one
DELETE FROM category
WHERE
  id = $1
RETURNING
  id, created_at, updated_at, name, romaji_name
`

func (q *Queries) DeleteCategoryByID(ctx context.Context, id int32) (Category, error) {
	row := q.db.QueryRowContext(ctx, deleteCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.RomajiName,
	)
	return i, err
}

const getCategories = `-- name: GetCategories :many
SELECT
  id, created_at, updated_at, name, romaji_name
FROM
  category
`

func (q *Queries) GetCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.RomajiName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetCategoryRows = `-- name: ResetCategoryRows :exec
DELETE FROM category
`

func (q *Queries) ResetCategoryRows(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetCategoryRows)
	return err
}

const updateCategoryByID = `-- name: UpdateCategoryByID :exec
UPDATE category
SET
  update_at = NOW(),
  name = $1,
  romaji_name = $2
WHERE
  id = $3
`

type UpdateCategoryByIDParams struct {
	Name       string
	RomajiName string
	ID         int32
}

func (q *Queries) UpdateCategoryByID(ctx context.Context, arg UpdateCategoryByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateCategoryByID, arg.Name, arg.RomajiName, arg.ID)
	return err
}
