// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BulkCreateCategoriesParams struct {
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	Name        string
	EnglishName pgtype.Text
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO
  categories (created_at, updated_at, name, english_name)
VALUES
  (NOW(), NOW(), $1, $2)
RETURNING
  id, created_at, updated_at, name, english_name
`

type CreateCategoryParams struct {
	Name        string
	EnglishName pgtype.Text
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.EnglishName)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.EnglishName,
	)
	return i, err
}

const deleteCategoriesByID = `-- name: DeleteCategoriesByID :exec
DELETE FROM categories
WHERE
  id = ANY ($1::int[])
`

func (q *Queries) DeleteCategoriesByID(ctx context.Context, dollar_1 []int32) error {
	_, err := q.db.Exec(ctx, deleteCategoriesByID, dollar_1)
	return err
}

const deleteCategoryByID = `-- name: DeleteCategoryByID :one
DELETE FROM categories
WHERE
  id = $1
RETURNING
  id, created_at, updated_at, name, english_name
`

func (q *Queries) DeleteCategoryByID(ctx context.Context, id int32) (Category, error) {
	row := q.db.QueryRow(ctx, deleteCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.EnglishName,
	)
	return i, err
}

const getCategories = `-- name: GetCategories :many
SELECT
  id, created_at, updated_at, name, english_name
FROM
  categories
ORDER BY
  id ASC
`

func (q *Queries) GetCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.EnglishName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetCategoryRows = `-- name: ResetCategoryRows :exec
DELETE FROM categories
`

func (q *Queries) ResetCategoryRows(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetCategoryRows)
	return err
}

const updateCategoryByID = `-- name: UpdateCategoryByID :exec
UPDATE categories
SET
  updated_at = NOW(),
  name = $1,
  english_name = $2
WHERE
  id = $3
`

type UpdateCategoryByIDParams struct {
	Name        string
	EnglishName pgtype.Text
	ID          int32
}

func (q *Queries) UpdateCategoryByID(ctx context.Context, arg UpdateCategoryByIDParams) error {
	_, err := q.db.Exec(ctx, updateCategoryByID, arg.Name, arg.EnglishName, arg.ID)
	return err
}
