// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package database

import (
	"context"
)

// iteratorForBulkCreateCategories implements pgx.CopyFromSource.
type iteratorForBulkCreateCategories struct {
	rows                 []BulkCreateCategoriesParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkCreateCategories) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkCreateCategories) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].CreatedAt,
		r.rows[0].UpdatedAt,
		r.rows[0].Name,
		r.rows[0].EnglishName,
	}, nil
}

func (r iteratorForBulkCreateCategories) Err() error {
	return nil
}

func (q *Queries) BulkCreateCategories(ctx context.Context, arg []BulkCreateCategoriesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"categories"}, []string{"created_at", "updated_at", "name", "english_name"}, &iteratorForBulkCreateCategories{rows: arg})
}

// iteratorForBulkCreateProducts implements pgx.CopyFromSource.
type iteratorForBulkCreateProducts struct {
	rows                 []BulkCreateProductsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkCreateProducts) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkCreateProducts) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].CreatedAt,
		r.rows[0].UpdatedAt,
		r.rows[0].Name,
		r.rows[0].EnglishName,
		r.rows[0].Price,
		r.rows[0].CategoryID,
		r.rows[0].Discount,
	}, nil
}

func (r iteratorForBulkCreateProducts) Err() error {
	return nil
}

func (q *Queries) BulkCreateProducts(ctx context.Context, arg []BulkCreateProductsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"products"}, []string{"created_at", "updated_at", "name", "english_name", "price", "category_id", "discount"}, &iteratorForBulkCreateProducts{rows: arg})
}
