// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Product struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Price     int32
	Discount  sql.NullInt32
}
