// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Category struct {
	ID         int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Name       string
	RomajiName string
}

type Product struct {
	ID         int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Name       string
	RomajiName string
	Price      int32
	CategoryID sql.NullInt32
	Discount   sql.NullInt32
}
