// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BulkCreateOrderItemParams struct {
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	OrderID   uuid.UUID
	ProductID int32
	Quantity  int32
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO
  orders (id, created_at, updated_at, table_id)
VALUES
  ($1, NOW(), NOW(), $2)
RETURNING
  id, created_at, updated_at, table_id, order_complete
`

type CreateOrderParams struct {
	ID      uuid.UUID
	TableID int32
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.ID, arg.TableID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TableID,
		&i.OrderComplete,
	)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM orders
WHERE
  id = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrder, id)
	return err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT
  id, created_at, updated_at, table_id, order_complete
FROM
  orders
WHERE
  id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TableID,
		&i.OrderComplete,
	)
	return i, err
}

const getOrders = `-- name: GetOrders :many
SELEcT
  id, created_at, updated_at, table_id, order_complete
FROM
  orders
`

func (q *Queries) GetOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TableID,
			&i.OrderComplete,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orderComplete = `-- name: OrderComplete :one
UPDATE orders
SET
  order_complete = $1
WHERE
  id = $2
RETURNING
  id, created_at, updated_at, table_id, order_complete
`

type OrderCompleteParams struct {
	OrderComplete bool
	ID            uuid.UUID
}

func (q *Queries) OrderComplete(ctx context.Context, arg OrderCompleteParams) (Order, error) {
	row := q.db.QueryRow(ctx, orderComplete, arg.OrderComplete, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TableID,
		&i.OrderComplete,
	)
	return i, err
}
