// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package database

import (
	"context"
	"database/sql"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO
  product (created_at, updated_at, name, price, discount)
VALUEs
  (NOW(), NOW(), $1, $2, $3)
RETURNING
  id, created_at, updated_at, name, price, discount
`

type CreateProductParams struct {
	Name     string
	Price    int32
	Discount sql.NullInt32
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct, arg.Name, arg.Price, arg.Discount)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Price,
		&i.Discount,
	)
	return i, err
}

const deleteProductByID = `-- name: DeleteProductByID :exec
DELETE FROM product
WHERE
  id = $1
`

func (q *Queries) DeleteProductByID(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteProductByID, id)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT
  id, created_at, updated_at, name, price, discount
FROM
  product
WHERE
  id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Price,
		&i.Discount,
	)
	return i, err
}

const getProducts = `-- name: GetProducts :many
SElECT
  id, created_at, updated_at, name, price, discount
FROM
  product
`

func (q *Queries) GetProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Price,
			&i.Discount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetProductRows = `-- name: ResetProductRows :exec
DELETE FROM product
`

func (q *Queries) ResetProductRows(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetProductRows)
	return err
}

const updateDiscount = `-- name: UpdateDiscount :exec
UPDATE product
SET
  updated_at = NOW(),
  discount = $1
WHERE
  id = $2
`

type UpdateDiscountParams struct {
	Discount sql.NullInt32
	ID       int32
}

func (q *Queries) UpdateDiscount(ctx context.Context, arg UpdateDiscountParams) error {
	_, err := q.db.ExecContext(ctx, updateDiscount, arg.Discount, arg.ID)
	return err
}
