// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BulkCreateProductsParams struct {
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	Name        string
	EnglishName string
	Price       int32
	CategoryID  int32
	Discount    int32
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO
  products (
    created_at,
    updated_at,
    name,
    english_name,
    price,
    category_id,
    discount
  )
VALUES
  (NOW(), NOW(), $1, $2, $3, $4, $5)
RETURNING
  id, created_at, updated_at, name, english_name, price, category_id, discount
`

type CreateProductParams struct {
	Name        string
	EnglishName string
	Price       int32
	CategoryID  int32
	Discount    int32
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.EnglishName,
		arg.Price,
		arg.CategoryID,
		arg.Discount,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.EnglishName,
		&i.Price,
		&i.CategoryID,
		&i.Discount,
	)
	return i, err
}

const deleteProductByID = `-- name: DeleteProductByID :exec
DELETE FROM products
WHERE
  id = $1
`

func (q *Queries) DeleteProductByID(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteProductByID, id)
	return err
}

const deleteProductsByID = `-- name: DeleteProductsByID :exec
DELETE FROM products
WHERE
  id = ANY ($1::int[])
`

func (q *Queries) DeleteProductsByID(ctx context.Context, dollar_1 []int32) error {
	_, err := q.db.Exec(ctx, deleteProductsByID, dollar_1)
	return err
}

const getProductByCategoryID = `-- name: GetProductByCategoryID :many
SELECT
  id, created_at, updated_at, name, english_name, price, category_id, discount
FROM
  products
WHERE
  category_id = $1
`

func (q *Queries) GetProductByCategoryID(ctx context.Context, categoryID int32) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductByCategoryID, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.EnglishName,
			&i.Price,
			&i.CategoryID,
			&i.Discount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT
  id, created_at, updated_at, name, english_name, price, category_id, discount
FROM
  products
WHERE
  id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.EnglishName,
		&i.Price,
		&i.CategoryID,
		&i.Discount,
	)
	return i, err
}

const getProductJoinByID = `-- name: GetProductJoinByID :one
SELECT
  products.id, products.created_at, products.updated_at, products.name, products.english_name, products.price, products.category_id, products.discount,
  categories.name AS category_name
FROM
  products
  INNER JOIN categories ON products.category_id = categories.id
WHERE
  products.id = $1
`

type GetProductJoinByIDRow struct {
	ID           int32
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	Name         string
	EnglishName  string
	Price        int32
	CategoryID   int32
	Discount     int32
	CategoryName string
}

func (q *Queries) GetProductJoinByID(ctx context.Context, id int32) (GetProductJoinByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductJoinByID, id)
	var i GetProductJoinByIDRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.EnglishName,
		&i.Price,
		&i.CategoryID,
		&i.Discount,
		&i.CategoryName,
	)
	return i, err
}

const getProducts = `-- name: GetProducts :many
SElECT
  id, created_at, updated_at, name, english_name, price, category_id, discount
FROM
  products
`

func (q *Queries) GetProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.EnglishName,
			&i.Price,
			&i.CategoryID,
			&i.Discount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsByID = `-- name: GetProductsByID :many
SELECT
  id, created_at, updated_at, name, english_name, price, category_id, discount
FROM
  products
WHERE
  id = ANY ($1::int[])
`

func (q *Queries) GetProductsByID(ctx context.Context, dollar_1 []int32) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductsByID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.EnglishName,
			&i.Price,
			&i.CategoryID,
			&i.Discount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsJoin = `-- name: GetProductsJoin :many
SELECT
  products.id, products.created_at, products.updated_at, products.name, products.english_name, products.price, products.category_id, products.discount,
  categories.name AS category_name
FROM
  products
  INNER JOIN categories ON products.category_id = categories.id
ORDER BY
  products.id ASC
`

type GetProductsJoinRow struct {
	ID           int32
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	Name         string
	EnglishName  string
	Price        int32
	CategoryID   int32
	Discount     int32
	CategoryName string
}

func (q *Queries) GetProductsJoin(ctx context.Context) ([]GetProductsJoinRow, error) {
	rows, err := q.db.Query(ctx, getProductsJoin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsJoinRow
	for rows.Next() {
		var i GetProductsJoinRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.EnglishName,
			&i.Price,
			&i.CategoryID,
			&i.Discount,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetProductsRows = `-- name: ResetProductsRows :exec
DELETE FROM products
`

func (q *Queries) ResetProductsRows(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetProductsRows)
	return err
}

const updateDiscount = `-- name: UpdateDiscount :exec
UPDATE products
SET
  updated_at = NOW(),
  discount = $1
WHERE
  id = $2
`

type UpdateDiscountParams struct {
	Discount int32
	ID       int32
}

func (q *Queries) UpdateDiscount(ctx context.Context, arg UpdateDiscountParams) error {
	_, err := q.db.Exec(ctx, updateDiscount, arg.Discount, arg.ID)
	return err
}

const updateProductByID = `-- name: UpdateProductByID :one
UPDATE products
SET
  updated_at = NOW(),
  name = $1,
  price = $2,
  category_id = $3,
  discount = $4,
  english_name = $5
WHERE
  id = $6
RETURNING
  id, created_at, updated_at, name, english_name, price, category_id, discount
`

type UpdateProductByIDParams struct {
	Name        string
	Price       int32
	CategoryID  int32
	Discount    int32
	EnglishName string
	ID          int32
}

func (q *Queries) UpdateProductByID(ctx context.Context, arg UpdateProductByIDParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductByID,
		arg.Name,
		arg.Price,
		arg.CategoryID,
		arg.Discount,
		arg.EnglishName,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.EnglishName,
		&i.Price,
		&i.CategoryID,
		&i.Discount,
	)
	return i, err
}
